"""empty message

Revision ID: 757689fa0a26
Revises: 6b8e93cad24d
Create Date: 2023-02-18 02:55:03.523265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757689fa0a26'
down_revision = '6b8e93cad24d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__users__id'), 'users', ['id'])
    op.create_unique_constraint(op.f('uq__users__nickname'), 'users', ['nickname'])
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', sa.VARCHAR(length=30), nullable=False),
    sa.Column('brief_information', sa.TEXT(), nullable=True),
    sa.Column('descrip_problem', sa.TEXT(), nullable=True),
    sa.Column('primary_goal', sa.TEXT(), nullable=True),
    sa.Column('major_groups', sa.TEXT(), nullable=True),
    sa.Column('implementation_experience', sa.TEXT(), nullable=True),
    sa.Column('project_potential', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.nickname'], name=op.f('fk__project__author__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__project')),
    sa.UniqueConstraint('id', name=op.f('uq__project__id'))
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__nickname'), 'users', type_='unique')
    op.drop_constraint(op.f('uq__users__id'), 'users', type_='unique')
    op.drop_table('project')
    # ### end Alembic commands ###
